### ISSUE TITLE
Some problems during training

### ISSUE THREAD

**Issue by fallpavilion** [lsa1997/POP#4]
Hi! Thank you for your great work.
When I tried to replicate your work, I encountered the following problem.
_______________________________________________________________________________________
Traceback (most recent call last):
  File "train_base.py", line 320, in <module>
    main()
  File "train_base.py", line 291, in main
    logger.info('>>>>>>> ------------------- <<<<<<<')
  File "/home2/hkz/nips24/POP-main/engine.py", line 137, in __exit__
    torch.cuda.empty_cache()
  File "/home/hkz/miniconda3/envs/pop2/lib/python3.6/site-packages/torch/cuda/memory.py", line 114, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: device-side assert triggered
_______________________________________________________________________________________

Have you encountered similar problems in the course of training? If it's convenient, please let me know which GPU you're using. Thank you !!!
![Uploading 问题pop.jpg…]()

**Comment by fallpavilion** [comment]
I'm sorry I didn't successfully upload my mature results screenshot, so I've re-raised an issue. I'm terribly sorry.
